<HTML>
<HEAD>
  <TITLE>Main Page &mdash; ${app} ${version}</TITLE>
  <LINK REL="STYLESHEET" TYPE="text/css" HREF="css/ARLogAnalyzer.css">
</HEAD>
<FRAMESET rows="6%,*" frameborder="no">
  <FRAMESET cols="100%,*">
    <FRAME name="title_frame" src="title.html" scrolling="no">
  </FRAMESET>
  <FRAMESET cols="15%,*">
    <FRAME name="sidebar_frame" src="sidebar.html">
    <FRAME name="details_frame" src="general_stats.html" scrolling="yes">
  </FRAMESET>
</FRAMESET>
</HTML>
