apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "remedyiq.apiServiceAccountName" . }}
  labels:
    {{- include "remedyiq.apiLabels" . | nindent 4 }}
automountServiceAccountToken: true
