apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "remedyiq.fullname" . }}-bleve-index
  labels:
    {{- include "remedyiq.workerLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.worker.bleveStorage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.worker.bleveStorage.size }}
