apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "remedyiq.workerServiceAccountName" . }}
  labels:
    {{- include "remedyiq.workerLabels" . | nindent 4 }}
automountServiceAccountToken: true
